# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\User\Desktop\COMP3278 - DBMS\Final Debugged Project\COMP3278_Project\COMP3278_Project\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1256, 713)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(25, 25, 25);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_header = QtWidgets.QFrame(self.centralwidget)
        self.main_header.setMinimumSize(QtCore.QSize(0, 0))
        self.main_header.setMaximumSize(QtCore.QSize(16777215, 50))
        self.main_header.setStyleSheet("QFrame{\n"
"    border-bottom: 1px solid #000;\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.main_header.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.main_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_header.setObjectName("main_header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tittle_bar_container = QtWidgets.QFrame(self.main_header)
        self.tittle_bar_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tittle_bar_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tittle_bar_container.setObjectName("tittle_bar_container")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tittle_bar_container)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.left_menu_toggle = QtWidgets.QFrame(self.tittle_bar_container)
        self.left_menu_toggle.setMinimumSize(QtCore.QSize(50, 0))
        self.left_menu_toggle.setMaximumSize(QtCore.QSize(50, 16777215))
        self.left_menu_toggle.setStyleSheet("QFrame{\n"
"    background-color: #000;\n"
"}\n"
"QPushButton{\n"
"    padding: 5px 10px;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    background-color: #000;\n"
"    color: #fff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 92, 157);\n"
"}")
        self.left_menu_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_toggle.setObjectName("left_menu_toggle")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.left_menu_toggle)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_5.addWidget(self.left_menu_toggle)
        self.tittle_bar = QtWidgets.QFrame(self.tittle_bar_container)
        self.tittle_bar.setEnabled(True)
        self.tittle_bar.setAutoFillBackground(False)
        self.tittle_bar.setStyleSheet("QLabel{\n"
"    color: #fff;\n"
"}")
        self.tittle_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tittle_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tittle_bar.setObjectName("tittle_bar")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tittle_bar)
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_9.setContentsMargins(11, -1, -1, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.tittle_bar)
        self.label_6.setMinimumSize(QtCore.QSize(1076, 20))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.horizontalLayout_5.addWidget(self.tittle_bar)
        self.horizontalLayout_2.addWidget(self.tittle_bar_container)
        self.top_right_btns = QtWidgets.QFrame(self.main_header)
        self.top_right_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.top_right_btns.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 92, 157);\n"
"}")
        self.top_right_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_right_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_right_btns.setObjectName("top_right_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.top_right_btns)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2.addWidget(self.top_right_btns)
        self.verticalLayout.addWidget(self.main_header)
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setStyleSheet("")
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.center_main_items = QtWidgets.QFrame(self.main_body)
        self.center_main_items.setStyleSheet("")
        self.center_main_items.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.center_main_items.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center_main_items.setObjectName("center_main_items")
        self.stackedWidget = QtWidgets.QStackedWidget(self.center_main_items)
        self.stackedWidget.setGeometry(QtCore.QRect(90, 10, 943, 585))
        self.stackedWidget.setObjectName("stackedWidget")
        self.accounts_page = QtWidgets.QWidget()
        self.accounts_page.setStyleSheet("")
        self.accounts_page.setObjectName("accounts_page")
        self.formLayout_3 = QtWidgets.QFormLayout(self.accounts_page)
        self.formLayout_3.setObjectName("formLayout_3")
        self.widget = QtWidgets.QWidget(self.accounts_page)
        self.widget.setMinimumSize(QtCore.QSize(791, 521))
        self.widget.setMaximumSize(QtCore.QSize(791, 521))
        self.widget.setObjectName("widget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(34, 34, 34);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid rgb(0, 93, 159);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color: rgb(0, 69, 116);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(206, 206, 206);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(14, 13, 24);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLabel{\n"
"    border:3px solid  rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(6, 63, 104);\n"
"}\n"
"QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 10px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 93, 159);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    background:rgb(0, 0, 0);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(34, 34, 34);\n"
"    background-image: url(:/icons/icons/cil-check.png);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.user = QtWidgets.QLabel(self.frame)
        self.user.setGeometry(QtCore.QRect(220, 250, 100, 50))
        self.user.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.user.setFont(font)
        self.user.setStyleSheet("")
        self.user.setAlignment(QtCore.Qt.AlignCenter)
        self.user.setObjectName("user")
        self.user_name_input = QtWidgets.QLineEdit(self.frame)
        self.user_name_input.setGeometry(QtCore.QRect(360, 250, 200, 54))
        self.user_name_input.setMinimumSize(QtCore.QSize(200, 50))
        self.user_name_input.setMaximumSize(QtCore.QSize(200, 16777215))
        self.user_name_input.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;")
        self.user_name_input.setAlignment(QtCore.Qt.AlignCenter)
        self.user_name_input.setObjectName("user_name_input")
        self.login_button = QtWidgets.QPushButton(self.frame)
        self.login_button.setGeometry(QtCore.QRect(490, 320, 68, 50))
        self.login_button.setMinimumSize(QtCore.QSize(0, 50))
        self.login_button.setMaximumSize(QtCore.QSize(200, 16777215))
        self.login_button.setObjectName("login_button")
        self.welcome_to_icms = QtWidgets.QTextEdit(self.frame)
        self.welcome_to_icms.setGeometry(QtCore.QRect(14, 40, 741, 171))
        self.welcome_to_icms.setObjectName("welcome_to_icms")
        self.verticalLayout_13.addWidget(self.frame)
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.widget)
        self.stackedWidget.addWidget(self.accounts_page)
        self.course_info = QtWidgets.QWidget()
        self.course_info.setStyleSheet("")
        self.course_info.setObjectName("course_info")
        self.formLayout_4 = QtWidgets.QFormLayout(self.course_info)
        self.formLayout_4.setObjectName("formLayout_4")
        self.input_fileds_frame = QtWidgets.QFrame(self.course_info)
        self.input_fileds_frame.setMinimumSize(QtCore.QSize(911, 561))
        self.input_fileds_frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(34, 34, 34);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid rgb(0, 93, 159);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color: rgb(0, 69, 116);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(206, 206, 206);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(14, 13, 24);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLabel{\n"
"    border:3px solid  rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(6, 63, 104);\n"
"}\n"
"QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 10px;\n"
"}\n"
"QTextEdit{\n"
"    border: none;\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 93, 159);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    background:rgb(0, 0, 0);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(34, 34, 34);\n"
"    background-image: url(:/icons/icons/cil-check.png);\n"
"}")
        self.input_fileds_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_fileds_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_fileds_frame.setObjectName("input_fileds_frame")
        self.welcome = QtWidgets.QTextEdit(self.input_fileds_frame)
        self.welcome.setGeometry(QtCore.QRect(30, 20, 851, 61))
        self.welcome.setObjectName("welcome")
        self.time_now = QtWidgets.QTextEdit(self.input_fileds_frame)
        self.time_now.setGeometry(QtCore.QRect(30, 80, 711, 51))
        self.time_now.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.time_now.setObjectName("time_now")
        self.whether_have_class = QtWidgets.QTextEdit(self.input_fileds_frame)
        self.whether_have_class.setGeometry(QtCore.QRect(30, 130, 491, 81))
        self.whether_have_class.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.whether_have_class.setObjectName("whether_have_class")
        self.course_code = QtWidgets.QTextEdit(self.input_fileds_frame)
        self.course_code.setGeometry(QtCore.QRect(30, 210, 571, 61))
        self.course_code.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.course_code.setObjectName("course_code")
        self.lecture_notes = QtWidgets.QTextEdit(self.input_fileds_frame)
        self.lecture_notes.setGeometry(QtCore.QRect(30, 290, 141, 161))
        self.lecture_notes.setObjectName("lecture_notes")
        self.tutorial_notes = QtWidgets.QTextEdit(self.input_fileds_frame)
        self.tutorial_notes.setGeometry(QtCore.QRect(210, 290, 141, 161))
        self.tutorial_notes.setObjectName("tutorial_notes")
        self.others = QtWidgets.QTextEdit(self.input_fileds_frame)
        self.others.setGeometry(QtCore.QRect(410, 290, 141, 161))
        self.others.setObjectName("others")
        self.latest_message = QtWidgets.QTextEdit(self.input_fileds_frame)
        self.latest_message.setGeometry(QtCore.QRect(690, 390, 201, 141))
        self.latest_message.setStyleSheet("QFrame{\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"}")
        self.latest_message.setObjectName("latest_message")
        self.zoom_link = QtWidgets.QTextEdit(self.input_fileds_frame)
        self.zoom_link.setGeometry(QtCore.QRect(690, 150, 201, 231))
        self.zoom_link.setStyleSheet("QFrame{\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"}")
        self.zoom_link.setObjectName("zoom_link")
        self.email_button_2 = QtWidgets.QPushButton(self.input_fileds_frame)
        self.email_button_2.setGeometry(QtCore.QRect(730, 80, 141, 51))
        self.email_button_2.setObjectName("email_button_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.input_fileds_frame)
        self.stackedWidget.addWidget(self.course_info)
        self.timetable = QtWidgets.QWidget()
        self.timetable.setObjectName("timetable")
        self.input_fileds_frame_2 = QtWidgets.QFrame(self.timetable)
        self.input_fileds_frame_2.setGeometry(QtCore.QRect(20, 0, 911, 561))
        self.input_fileds_frame_2.setMinimumSize(QtCore.QSize(911, 561))
        self.input_fileds_frame_2.setMaximumSize(QtCore.QSize(911, 561))
        self.input_fileds_frame_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(34, 34, 34);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid rgb(0, 93, 159);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color: rgb(0, 69, 116);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(206, 206, 206);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(14, 13, 24);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLabel{\n"
"    border:3px solid  rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(6, 63, 104);\n"
"}\n"
"QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 10px;\n"
"}\n"
"QTextEdit{\n"
"    border: none;\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 93, 159);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    background:rgb(0, 0, 0);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(34, 34, 34);\n"
"    background-image: url(:/icons/icons/cil-check.png);\n"
"}")
        self.input_fileds_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_fileds_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_fileds_frame_2.setObjectName("input_fileds_frame_2")
        self.welcome_2 = QtWidgets.QTextEdit(self.input_fileds_frame_2)
        self.welcome_2.setGeometry(QtCore.QRect(30, 20, 851, 61))
        self.welcome_2.setObjectName("welcome_2")
        self.time_now_2 = QtWidgets.QTextEdit(self.input_fileds_frame_2)
        self.time_now_2.setGeometry(QtCore.QRect(30, 90, 501, 31))
        self.time_now_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.time_now_2.setObjectName("time_now_2")
        self.below_timetable = QtWidgets.QTextEdit(self.input_fileds_frame_2)
        self.below_timetable.setGeometry(QtCore.QRect(30, 130, 511, 41))
        self.below_timetable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.below_timetable.setObjectName("below_timetable")
        self.weekly_timetable = QtWidgets.QTextEdit(self.input_fileds_frame_2)
        self.weekly_timetable.setGeometry(QtCore.QRect(30, 180, 861, 311))
        self.weekly_timetable.setObjectName("weekly_timetable")
        self.email_button = QtWidgets.QPushButton(self.input_fileds_frame_2)
        self.email_button.setGeometry(QtCore.QRect(740, 80, 131, 51))
        self.email_button.setObjectName("email_button")
        self.stackedWidget.addWidget(self.timetable)
        self.activity_record = QtWidgets.QWidget()
        self.activity_record.setObjectName("activity_record")
        self.frame_2 = QtWidgets.QFrame(self.activity_record)
        self.frame_2.setGeometry(QtCore.QRect(120, 50, 581, 531))
        self.frame_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(34, 34, 34);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.activity_record_text = QtWidgets.QTextEdit(self.frame_2)
        self.activity_record_text.setGeometry(QtCore.QRect(0, 0, 581, 71))
        self.activity_record_text.setStyleSheet("")
        self.activity_record_text.setObjectName("activity_record_text")
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setGeometry(QtCore.QRect(280, 70, 16, 461))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.date_and_time = QtWidgets.QTextEdit(self.frame_2)
        self.date_and_time.setGeometry(QtCore.QRect(40, 80, 201, 41))
        self.date_and_time.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.date_and_time.setObjectName("date_and_time")
        self.activity = QtWidgets.QTextEdit(self.frame_2)
        self.activity.setGeometry(QtCore.QRect(340, 80, 191, 41))
        self.activity.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.activity.setObjectName("activity")
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(0, 70, 581, 61))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame_2)
        self.line_3.setGeometry(QtCore.QRect(0, 180, 581, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.frame_2)
        self.line_4.setGeometry(QtCore.QRect(0, 250, 581, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.frame_2)
        self.line_5.setGeometry(QtCore.QRect(0, 320, 581, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.frame_2)
        self.line_6.setGeometry(QtCore.QRect(0, 390, 581, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.frame_2)
        self.line_7.setGeometry(QtCore.QRect(0, 460, 581, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.date_0 = QtWidgets.QTextEdit(self.frame_2)
        self.date_0.setGeometry(QtCore.QRect(10, 140, 241, 31))
        self.date_0.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.date_0.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.date_0.setObjectName("date_0")
        self.date_1 = QtWidgets.QTextEdit(self.frame_2)
        self.date_1.setGeometry(QtCore.QRect(10, 210, 241, 31))
        self.date_1.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.date_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.date_1.setObjectName("date_1")
        self.date_2 = QtWidgets.QTextEdit(self.frame_2)
        self.date_2.setGeometry(QtCore.QRect(10, 280, 241, 31))
        self.date_2.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.date_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.date_2.setObjectName("date_2")
        self.date_3 = QtWidgets.QTextEdit(self.frame_2)
        self.date_3.setGeometry(QtCore.QRect(10, 350, 241, 31))
        self.date_3.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.date_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.date_3.setObjectName("date_3")
        self.date_4 = QtWidgets.QTextEdit(self.frame_2)
        self.date_4.setGeometry(QtCore.QRect(10, 420, 241, 31))
        self.date_4.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.date_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.date_4.setObjectName("date_4")
        self.date_5 = QtWidgets.QTextEdit(self.frame_2)
        self.date_5.setGeometry(QtCore.QRect(10, 490, 241, 31))
        self.date_5.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.date_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.date_5.setObjectName("date_5")
        self.activity_0 = QtWidgets.QTextEdit(self.frame_2)
        self.activity_0.setGeometry(QtCore.QRect(310, 140, 241, 31))
        self.activity_0.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.activity_0.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.activity_0.setObjectName("activity_0")
        self.activity_1 = QtWidgets.QTextEdit(self.frame_2)
        self.activity_1.setGeometry(QtCore.QRect(310, 210, 241, 31))
        self.activity_1.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.activity_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.activity_1.setObjectName("activity_1")
        self.activity_2 = QtWidgets.QTextEdit(self.frame_2)
        self.activity_2.setGeometry(QtCore.QRect(310, 280, 241, 31))
        self.activity_2.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.activity_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.activity_2.setObjectName("activity_2")
        self.activity_3 = QtWidgets.QTextEdit(self.frame_2)
        self.activity_3.setGeometry(QtCore.QRect(310, 350, 241, 31))
        self.activity_3.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.activity_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.activity_3.setObjectName("activity_3")
        self.activity_4 = QtWidgets.QTextEdit(self.frame_2)
        self.activity_4.setGeometry(QtCore.QRect(310, 420, 241, 31))
        self.activity_4.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.activity_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.activity_4.setObjectName("activity_4")
        self.activity_5 = QtWidgets.QTextEdit(self.frame_2)
        self.activity_5.setGeometry(QtCore.QRect(310, 490, 241, 31))
        self.activity_5.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.activity_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.activity_5.setObjectName("activity_5")
        self.line_2.raise_()
        self.activity_record_text.raise_()
        self.line.raise_()
        self.date_and_time.raise_()
        self.activity.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.date_0.raise_()
        self.date_1.raise_()
        self.date_2.raise_()
        self.date_3.raise_()
        self.date_4.raise_()
        self.date_5.raise_()
        self.activity_0.raise_()
        self.activity_1.raise_()
        self.activity_2.raise_()
        self.activity_3.raise_()
        self.activity_4.raise_()
        self.activity_5.raise_()
        self.stackedWidget.addWidget(self.activity_record)
        self.left_menu_top_buttons = QtWidgets.QFrame(self.center_main_items)
        self.left_menu_top_buttons.setGeometry(QtCore.QRect(10, 0, 71, 608))
        self.left_menu_top_buttons.setMinimumSize(QtCore.QSize(43, 316))
        self.left_menu_top_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_top_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_top_buttons.setObjectName("left_menu_top_buttons")
        self.accounts_button = QtWidgets.QPushButton(self.left_menu_top_buttons)
        self.accounts_button.setGeometry(QtCore.QRect(10, 0, 100, 56))
        self.accounts_button.setMinimumSize(QtCore.QSize(100, 0))
        self.accounts_button.setStyleSheet("background-image: url(:/icons/icons/cil-user.png);\n"
"background-repeat: none;\n"
"padding-left: 50px;\n"
"background-position: center left;")
        self.accounts_button.setObjectName("accounts_button")
        self.weekly_timetable_button = QtWidgets.QPushButton(self.left_menu_top_buttons)
        self.weekly_timetable_button.setGeometry(QtCore.QRect(10, 130, 41, 56))
        self.weekly_timetable_button.setStyleSheet("background-image: url(:/icons/icons/calendar.png);\n"
"background-repeat: none;\n"
"padding-left: 1000px;\n"
"background-position: center left;")
        self.weekly_timetable_button.setObjectName("weekly_timetable_button")
        self.activity_record_button = QtWidgets.QPushButton(self.left_menu_top_buttons)
        self.activity_record_button.setGeometry(QtCore.QRect(10, 210, 41, 56))
        self.activity_record_button.setStyleSheet("background-image: url(:/icons/icons/clock.png);\n"
"background-repeat: none;\n"
"padding-left: 1000px;\n"
"background-position: center left;")
        self.activity_record_button.setObjectName("activity_record_button")
        self.course_info_one_hour_button = QtWidgets.QPushButton(self.left_menu_top_buttons)
        self.course_info_one_hour_button.setGeometry(QtCore.QRect(10, 60, 41, 56))
        self.course_info_one_hour_button.setStyleSheet("background-image: url(:/icons/icons/course_info.png);\n"
"background-repeat: none;\n"
"padding-left: 1000px;\n"
"background-position: center left;")
        self.course_info_one_hour_button.setObjectName("course_info_one_hour_button")
        self.horizontalLayout.addWidget(self.center_main_items)
        self.verticalLayout.addWidget(self.main_body)
        self.main_footer = QtWidgets.QFrame(self.centralwidget)
        self.main_footer.setMinimumSize(QtCore.QSize(0, 50))
        self.main_footer.setMaximumSize(QtCore.QSize(16777215, 30))
        self.main_footer.setStyleSheet("QFrame{\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-top-color: solid 1px  rgb(0, 0, 0);\n"
"}\n"
"QLabel{\n"
"    color: #fff;\n"
"}")
        self.main_footer.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.main_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_footer.setObjectName("main_footer")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.main_footer)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout.addWidget(self.main_footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Intelligent Course Management System (ICMS)"))
        self.user.setText(_translate("MainWindow", "Username"))
        self.user_name_input.setPlaceholderText(_translate("MainWindow", "Username"))
        self.login_button.setText(_translate("MainWindow", "Login"))
        self.welcome_to_icms.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:26pt;\">Welcome to</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:26pt;\">HKU Intelligent Course Management System</span></p></body></html>"))
        self.welcome.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:24pt;\">Welcome Back, Frankie!</span></p></body></html>"))
        self.time_now.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:18pt;\">The time now is 2022-11-24 13:10</span></p></body></html>"))
        self.whether_have_class.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:16pt;\">You will have class COMP3278 at MTW2 in 20 minutes!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:16pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:16pt;\">Below is the course information:</span></p></body></html>"))
        self.course_code.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:14pt;\">2022    COMP3278    Introduction to Database Management System</span></p></body></html>"))
        self.lecture_notes.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:14pt;\">Lecture Notes</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:14pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:14pt; text-decoration: underline;\">Lecture_1.pdf</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:14pt; text-decoration: underline;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:14pt; text-decoration: underline;\">Lecture_2.pdf</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:14pt; text-decoration: underline;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:14pt; text-decoration: underline;\">Lecture_3.pdf</span></p></body></html>"))
        self.tutorial_notes.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:14pt;\">Tutroial Notes</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:14pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:14pt; text-decoration: underline;\">tutorial_1.pdf</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:14pt; text-decoration: underline;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:14pt; text-decoration: underline;\">tutorial_2.pdf</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:14pt; text-decoration: underline;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:14pt; text-decoration: underline;\">tutorial_3.pdf</span></p></body></html>"))
        self.others.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:14pt;\">Others</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:14pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:14pt; text-decoration: underline;\">Assignment1.pdf</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:14pt; text-decoration: underline;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:14pt; text-decoration: underline;\">Assignment2.pdf</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:14pt; text-decoration: underline;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:14pt; text-decoration: underline;\">Lab1.zip</span></p></body></html>"))
        self.latest_message.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:12pt;\">Latest Message from teacher</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:12pt;\">2022-11-23 17:10:33</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:13pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:10pt;\">Remember to bring your laptop in the next lecture!</span></p></body></html>"))
        self.zoom_link.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:12pt;\">Lecture Zoom Link</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:12pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:12pt;\">https://zoom.us/meeting/1234</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:12pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:12pt;\">Tutorial Zoom Link</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:12pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:12pt;\">https://zoom.us/meeting/2345</span></p></body></html>"))
        self.email_button_2.setText(_translate("MainWindow", "Email Information"))
        self.welcome_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:24pt;\">Welcome Back, Frankie!</span></p></body></html>"))
        self.time_now_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:18pt;\">The time now is 2022-11-24 13:10</span></p></body></html>"))
        self.below_timetable.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:18pt;\">Below is your timetable:</span></p></body></html>"))
        self.weekly_timetable.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:13pt;\">2022-11-24 Thursday</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:13pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:13pt;\">10:30 - 12:20  COMP2396  Intorduction to Java and OOP  at  CPDLG26</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:13pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:13pt;\">17:30 - 18:20  COMP2396  Intorduction to Java and OOP  at  CPDLG26</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:13pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:13pt;\">19:30 - 21:20  COMP2396  Intorduction to Java and OOP  at  MTW2</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:13pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:13pt;\">23:59               COMP3278  Assignement 3 dued</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:13pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:13pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:13pt;\">2022-11-25 Friday</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:13pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:13pt;\">10:30 - 12:20  COMP2396  Intorduction to Java and OOP  at  CPDLG26</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Roboto\'; font-size:13pt;\"><br /></p></body></html>"))
        self.email_button.setText(_translate("MainWindow", "Email timetable"))
        self.activity_record_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:24pt;\">Activity Record</span></p></body></html>"))
        self.date_and_time.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:14pt;\">Date and Time</span></p></body></html>"))
        self.activity.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:14pt;\">Activity</span></p></body></html>"))
        self.date_0.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:13pt;\">2022-11-24     14:50</span></p></body></html>"))
        self.date_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:13pt;\">2022-11-24     14:50</span></p></body></html>"))
        self.date_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:13pt;\">2022-11-24     14:50</span></p></body></html>"))
        self.date_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:13pt;\">2022-11-24     14:50</span></p></body></html>"))
        self.date_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:13pt;\">2022-11-24     14:50</span></p></body></html>"))
        self.date_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:13pt;\">2022-11-24     14:50</span></p></body></html>"))
        self.activity_0.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:13pt;\">Visited Activity Record</span></p></body></html>"))
        self.activity_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:13pt;\">View Course Info</span></p></body></html>"))
        self.activity_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:13pt;\">Login</span></p></body></html>"))
        self.activity_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:13pt;\">Visited Activity Record</span></p></body></html>"))
        self.activity_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:13pt;\">Visited Activity Record</span></p></body></html>"))
        self.activity_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Roboto\'; font-size:13pt;\">Visited Activity Record</span></p></body></html>"))
        self.accounts_button.setText(_translate("MainWindow", "ACCOUNT"))
        self.weekly_timetable_button.setText(_translate("MainWindow", "calendar"))
        self.activity_record_button.setText(_translate("MainWindow", "calendar"))
        self.course_info_one_hour_button.setText(_translate("MainWindow", "calendar"))
import icon_rc
